services:
  db:
    build: ./db
    volumes:
      - db_data:/var/lib/db
      - ./db/initialize.sql:/docker-entrypoint-initdb.d/initialize.sql
    restart: always
    environment:
      MYSQL_DATABASE: user
      MYSQL_ROOT_PASSWORD: password
    ports:
      - "3306:3306"

  backend:
    build: ./backend
    container_name: win95_api
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: "mysql://root:password@db:3306/user"
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: win95_client
    ports:
      - "5173:5173"
    command: ["bun", "run", "dev", "--host"]
volumes:
  db_data: {}